### ISSUE TITLE
Script hangs over UnsupportedOperation error by wrong AMI-instance type combination

### ISSUE THREAD

**Issue by bissim** [isislab-unisa/aws-build-cluster-script#4]
If an user requests an AMI with unsupported instance type, scripts properly returns due error, however it hangs waiting for creation of instances that will be never created.

For example, providing `ami-019af36249ca598da` (Ubuntu 18.04 LTS latest, up to day) and `t2.micro` instance type, since they're not compatible, script hangs on `>>> WAITING for the instances to become RUNNING`.

Eh @labgua?

**Comment by bissim** [comment]
You should halt execution of `make_cluster.sh` on line [74](https://github.com/isislab-unisa/aws-build-cluster-script/blob/e5ab23518004c9867a0a7764b2399f0e641b3a44/make_cluster.sh#L74) if `aws` command returns an error.

**Comment by bissim** [comment]
A simpler check you may perform is about the `data/id_instances.json` file: if it is empty, then aws command failed.
I may try to PR this for you.

**Comment by labgua** [comment]
Hi @bissim ,
I am happy to have received your issue.
Unfortunately many controls were not created because of the haste to finish the course, it will be my duty to grate some controls on the code.
I would have the pleasure of your collaboration: if you have proposals you make a pull request.
Give me time to try it.

Best Regards,
Sergio Guastaferro
